#!/bin/bash
# Logo Maker
clear
echo -e "${YELLOW} Aguarde, configurando Firewall"
echo -e "${DARK_GRAY} ${GREEN}
         .............................................  .           
    .......................................................         
   .......................................,.'..'.'......... ....    
  .........................:lodxkx,kxxddo;',;ccc:;:l'.o.l.o c:.c... 
 .............,......,lclxl,c:;;;;';;;;:c'oOc,;:.'.'..,.'.'.'..'..  
 ............ko.'.:dOd::;l:c,cc:::::::::cc'oc,...',,l:c.o.d.:'.c... 
............dc..ld;:,.l.  ...'loXWNWMMNko,o'      .:,.,.'.'....' .. 
.......,:...'.lOl,;ll':    :OWMMMMMMMMMMMO;        cooc.d.x.c,c;,'. 
.....;.,Ol'.,0d';c:oo;.. ;NMMMMMMMMMMMMMMMXl.    .l,'lKx'.'....,....
....'xk..xx''..:l;:lll:.:NMMMMMMMMMWWMMMMMWKx:..,c,llc,cx'l'l:.o.,..
......lO;.ck;.':o;llcl;xMMNxOWMMMWk:,:xWMMMMW0: 'Oc:lcc,xO,.,'.'....
.......,do.,x:.':co;,'lWMK.  XMMW0.    .OWMMMWXo'c0o;lcc,xd.'c::;,,.
....,;...dk'.x:.,c;:;;XMk. '.XWWNO. ;.   lWMMXOxO,o0;;ccc.xd.,',.'..
....K;.'c.cx''Oc'lll,cWMc  .XMMMMNk'     ;KMWWxodc;do'ccc:,X:.:c.,..
...:;...l0'c0,.Ol':l;,XWXd.KWWNXWN0xl',,l0WMK0Kox;,l0,cc:c'Od.',....
.......xd:0,;x:.ll.::.oXWK:'''..cNXkdokXWMWW0ddoo.:cOO':::;l0'.:....
.......0k.,k;;0c.xl.::.cOodWk,dKN0xcc,ooo0XOxodk: ..;Kx';:;;K,.,....
.....'.do.;,0:'O:.l;,c:.,l:lo,':;;:lllc:cddlod,,    ..:k;,,'k'.'....
.......x0.;,,x:'x',,.',:;;...kKXKkdol:ll;l,.,.     ... .d,.lO'.'....
.......:X:';''k:.',lc;;;codxc..,.'. ... . ..  .'  .. ....k.0d..'....
........0O.,;,'O,.,.;;;,,,,,:dl.         'k .. ;x    ..  ,l0;..'....
........,dl.,,..x' :. ......'';kO:      :OWkd:OXXl.   .  .x;.',,....
.........:Ko.'.:;O'. . ...  ....loOc.  d,'oo;.k:o.o'    .0o.',,,....
..........,kd.'. :d.;o.,...    ...':k:..  :cxW;l. .'   .ol..''.'....
............ok;   cx.ld.'...     ....':. .:dxokc,.   .lO:.'.''.'....
.............'c;.  cc.,:.''.           ..           .xl.............
.............. dXo ;K0:0X; .OXo:OXWNKd.     KX,'ONWN0'..............
 ..............kMOxMk. .0MxXW:dMX,..lMW'    WM;kM0,,, ..............
.............. kWMNWd    xMN' 0Mx ,;.NMc    NM;.lkKWNo .............
  ............ xNx dNK,  :W0  .0WOkWNNkc'kOoNW,d0ocONk .............
   ........... ,c, .,lc. .c: ...':ll:..c'.clc. .;clc,...............
   .................................................................
  ..................................................................
 ...................................................................
${RESET}"
sleep 2